version: '3.4'

networks:
  netzon.api-dev:
    driver: bridge

services:
  netzon.api:
    image: netzon.api:lastest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=netzon_api;username=openpg;password=openpgpwd"
    networks:
      - netzon.api-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "openpg"
      POSTGRES_PASSWORD: "openpgpwd"
      POSTGRES_DB: "netzon_api"
    networks:
      - netzon.api-dev
volumes:
  db_volume: